### ISSUE TITLE
Multiple monitor issue

### ISSUE THREAD

**Issue by Gabriele-LS** [rse/vingester#13]
Hello @rse, I have the following monitor setup.

![image](https://user-images.githubusercontent.com/67373152/114537333-5c9d5c00-9c52-11eb-865f-7cdbff54e592.png)

But I'm unable to properly position Vingester windows.

I used the following settings.

<img width="972" alt="Screenshot 2021-04-13 at 12 16 36" src="https://user-images.githubusercontent.com/67373152/114537455-835b9280-9c52-11eb-909f-14508092764d.png">

The -1,0 parameter works, but the -2,0 doesn't (the window appears on the main monitor).

**Comment by JBraddockm** [comment]
I only one external display at the moment so I can't test this but I was wondering if the video output could be similar to Audio Output selection i.e a dropdown menu with the names of connected displays. This is of course assuming that they operate similarly.

**Comment by rse** [comment]
The dropdown in general is a good idea, but unfortunately displays do not have a reasonable name or identifier. They just have an internal large numerical id which tells you nothing. So, the only thing which would make sense is to actually draw a tiny diagram of the display layout (similar to what the operating system do in its settings dialogs). So, for now I've to stick by addressing the displays with a "x,y" address because this always works.

**Comment by rse** [comment]
The implementation was buggy and hence did not allows "+2,0". This will be fixed with Vingester 1.5.4 in a few minutes.
