### ISSUE TITLE
How to use the new feature of recording (using ffmpeg) in mpegts format?

### ISSUE THREAD

**Issue by fboumol** [rse/vingester#26]
I am running the last version of Vingester (1.9.1. from 2021-05-04) in an ubuntu 18.04 machine (with xmonad as window manager).

Vingester is working fine as far as watching the streamings, but I am not able to record anything in any format (neither matroska, flv, etc.). I am particularly interested in the case of getting an mpegts file with the live streaming. I have selected what seems reasonable to me in the dialog but no file appears in ~/Videos

You can see [this dialog screenshot](https://imgur.com/a/FzHowJT) with my choices (but I have tried a lot of combinations, not just this one).

Could someone tell what I am doing wrong to get an mpegts file which records the streaming? Is there some verbose way to see why no file appears in my ~/Videos folder?

**Comment by rse** [comment]
According to your screenshot, the configuration looks fine. Internally, I use `electron.app.getPath("videos")` which at least under Windows and macOS points to the "Videos" or "Movies" directories in the home directory of the user. Perhaps under Linux it points to somewhere else. Try to enter a fully-qualified path as in "/home/<username>/test.mkv" and check whether it works at least this way. If this is the case, then we have just a path determination problem. If it still does not work, then the FFmpeg process does not work. I guess it is the FFmpeg process. Because from a different Electron app (LiVE Receiver) I know that the "ffmpeg" binaries available crash under some Linux systems. And I guess this is the problem here, too. The only workaround in this case is to install ffmpeg externally via the OS and then let Vingester fallback to this version of ffmpeg in case the embedded one crashes. The corresponding code is similar to what I've done for LiVE Receiver and what can be seen [here](https://github.com/rse/live-receiver/blob/5e35f3780d9c3a9b82a07224c761a60506fd0a8f/app-main-relay-videostream.js#L218]

**Comment by rse** [comment]
Ok, workaround for Linux (similar to what I did for my other electron app LiVE Receiver) is now applied. It will be part of the forthcoming version 2.0.0. If you want to test it in the meantime you would have to fetch the latest Vingester sources and build them locally. Alternatively, wait until I release 2.0.0 today or tomorrow and then recheck. Feel free to reopen this issue in case the problem then still exists.

**Comment by fboumol** [comment]
Let me say that with the old version absolute paths are neither working (I already tried without success). I will wait for the 2.0.0 release and I will tell you if this issue is solved.

By the way, is there some easy way to tell to use my local ffmpeg binary instead of the binary you provide?  Where is this configuration setting?

**Comment by rse** [comment]
The path to the ffmpeg binary is hard-coded in the sources of Vingester. You cannot easily change this. You can only build Vingester from source and this way change it
