### ISSUE TITLE
Bad quality in ffmpeg recordings

### ISSUE THREAD

**Issue by Gabriele-LS** [rse/vingester#27]
Hi @rse, I just tested the new (to me) ffmpeg output feature. Unfortunately, I was unable to get a good quality recording out of it. I'm using a MacBook Pro (16-inch, 2019) with macOS Big Sur 11.3.1.

These are my settings:

<img width="663" alt="Screenshot 2021-05-13 at 20 46 47" src="https://user-images.githubusercontent.com/67373152/118172440-a97c7a00-b42c-11eb-9f87-d41826eb5e27.png">

This is the output I got:

https://user-images.githubusercontent.com/67373152/118172670-ecd6e880-b42c-11eb-897a-1c8848981873.mp4

This is the URL I used for my test:

https://www.youtube.com/embed/V5Fsj_sCKdg?autoplay=1

**Comment by rse** [comment]
Yes, you're right: the output is not good enough. The problem seems to be that the source is a 4K 60fps video and we certainly need some more FFmpeg options to get good output quality in this situation. First, I selected "60" for the "Frame Rate" in Vingester and then I used the additional FFmpeg options "-b:v 20000k -maxrate 20000k -bufsize 40000k" to increase the bitrate. The output got better, but it's still not perfect. I'll check what one can further do here...

**Comment by rse** [comment]
Ok, Vingester 2.0.2 now contains a few different FFmpeg default options which should improve the situation. It's still not perfect, but better IMHO. But I'm currently unable (with my FFmpeg knowledge) to further improve the recording.

**Comment by Gabriele-LS** [comment]
I did a quick test. It seems much better. Thanks.

**Comment by rse** [comment]
I've tried to further improve the FFmpeg default options. As recording and streaming is too different, Vingester 2.1.0 now has an FFmpeg "Mode" field for controlling the defaults. One can still override everything with the "Arguments" field. But the default should be now even more reasonable. I'll close this issue for now. If you still have problems, feel free to reopen it.
