### ISSUE TITLE
Feature Request: no audio

### ISSUE THREAD

**Issue by rogue-ronin** [rse/vingester#28]
Hi again.

It's such a great app, but I need to bring in some feeds without audio landing in my default device (or my mixer.)

Could that be an option in the audio device dropdown?

Much aloha, and if no can, no worries!

**Comment by rse** [comment]
As you are talking about the "audio device dropdown" I assume you are using the Frameless mode of operation. Because for the Headless mode of operation you could choose "0" for the audio channels and this way no audio is sent. But for the Frameless mode you're right: we need a way to disable audio. I'll check what can be done here. A workaround for you is to use a Virtual Audio Cable which is NOT connected to a sink and send the output there.

**Comment by rse** [comment]
A "(none)" audio device can be now selected for Frameless mode in the soon to be released Vingester 2.0.1.

**Comment by rogue-ronin** [comment]
I didn't even have time to respond to you, and you've completed the request already.

Much aloha! and thank you again.

Oh, and I'm on Linux. I could mute the channel in pavucontrol, but that's awkward and out of sight and easy to forget...
