### ISSUE TITLE
Add Decklink support through Macadam

### ISSUE THREAD

**Issue by matiaspl** [rse/vingester#38]
Physical SDI outputs from Vingester would be a great addition to NDI. BMD Decklinks are by far the most common SDI IO cards in the market . Since you already use Grandiose, adding Macadam (https://www.npmjs.com/package/macadam) which uses pretty much the same concepts and API might not be a complex task.

**Comment by rse** [comment]
Currently I've no BMD Decklink cards at hand myself, so I cannot easily test this. And the Macadam (unlike my own Grandiose variant) seems to require a pre-installed BMD SDK. So, in order to provide SDI support, we would need a way to make Macacam behave similar to Grandiose (and on-the-fly download and just locally install BMD SDK) and then I would have to purchase some of those BMD cards, too.

OTOH, Vingester's output can be on HDMI and there exist decent HDMI to SDI converters (from BMD, Decimator, etc), so indirectly it is at least possible to send the Vingester output into productions via SDI, too.

So, for now I consider this a decent request, but one I cannot easily fulfill now. So please allow me to close this issue with "WONTFIX".
