### ISSUE TITLE
Apple M1 Support

### ISSUE THREAD

**Issue by thpryrchn** [rse/vingester#42]
Make a Apple silicone version, or a Universal Mac release.
I know that OBS doesn't have official M1 support yet, but They are getting close. There is an unofficial version here: https://www.reddit.com/r/obs/comments/njwbxl/compiling_obs_for_apple_silicon_m1/h2dw750

As native M1 compiled programs use less memory, and run more efficiently, It would be awesome if vingster could run in M1 Native Binary.

**Comment by rse** [comment]
Vingester is based on Electron and Electron exists for Apple M1 (arm64) now, of course. But there are two problems: (1) one cannot cross-build Vingester for arm64 on x64, because Vingester needs native Node modules (for NDI, Opus, etc) and those have to be compiled on the target platform, and (2) the underlying NewTek NDI SDK required is still not available for arm64. So, there is currently no chance to provide a native Apple M1 (arm64) version of Vingester. OTOH, the x64 version should run just fine, as the Apple Rosetto facility is able to translate x64 binaries to arm64 binaries in a very good way without really loosing much performance. So, I cannot resolve this issue now and hence allow me to close this issue.
