### ISSUE TITLE
Windows Security reports Trojan:Win32/Bulta!rfn on Vingester 2.6.6

### ISSUE THREAD

**Issue by me-vlad** [rse/vingester#54]
After update Vingester from 2.6.5 to 2.6.6 Windows Security quarantines Vingester.exe file

![image](https://user-images.githubusercontent.com/222185/136962265-c7f65d9b-ff5e-4297-91ea-7013ea9be273.png)

**Comment by rse** [comment]
Yes, AFAIK this is caused by the latest versions of Electron Builder. It already occurred once in the past (see https://github.com/electron-userland/electron-builder/issues/4793). AFAIK I cannot change anything on the Vingester side. Inside the Vingester code I can assure you that there is no such trojan. But once the Windows EXE is built by Electron Builder the Windows Security guard intercepts as it thinks this EXE has this trojan in it. I guess it is the same type of false positive which already happened in the past with Electron Builder based EXE files, but I've to investigate and crawl for more information...
