### ISSUE TITLE
Windows Defender recognizes latest release as malicious.

### ISSUE THREAD

**Issue by fabiankaestner** [rse/vingester#57]
Windows Defender recognizes the 2.6.7 Vingester build as Trojan:Win32/AgentTesla!ml.

![image](https://user-images.githubusercontent.com/8317993/141522967-519c3d50-d804-4f95-af80-879af1205ad7.png)

**Comment by rse** [comment]
This is a regularly occuring problem with Windows Defender. It regularly flags Electron-Builder based applications, like Vingester, as containing a trojan or a malware. The latest Vingester 2.7.0 at least passes the CURRENT Windows Defender state just fine. But it can be that in a few weeks also this version is flagged. It is always a false positive and the Electron-Builder people know the issue. I can also update to the latest Electron-Builder version and always hope the issue is gone (again).
