### ISSUE TITLE
Windows Defender disallows installation/opening of Vingester

### ISSUE THREAD

**Issue by lindenkron** [rse/vingester#65]
This didn't happen on older versions, but ever since I tried to update from 2.6.7 I believe, to current version, I cannot open zip files or install the software.
![image](https://user-images.githubusercontent.com/6466136/153322524-8219b2f2-4959-4b20-b5d3-53539cb9f260.png)

**Comment by rse** [comment]
Yes, this is the usual problem with unsigned Electron-Builder applications like Vingster. I'll upgrade to a newer version of Electron-Builder and then see whether this resolves the problem. Also, make sure you always have the latest Microsoft Defender updates applied to your system or it complain already because of these.
