### ISSUE TITLE
Vingester 1.4 user interface issue

### ISSUE THREAD

**Issue by Gabriele-LS** [rse/vingester#8]
Hello @rse. I just downloaded Vingester 1.4 and…

<img width="840" alt="Screenshot 2021-04-09 at 08 10 13" src="https://user-images.githubusercontent.com/67373152/114136518-2044c580-990b-11eb-8ba2-321d8eaabffb.png">

**Comment by JBraddockm** [comment]
Another interface issue: Close and minimise buttons for Mac are still present but the fullscreen button is removed. The release note suggests they should have all be removed. 

Since I can't make the Vingester window go fullscreen automatically - the menu bar is still present -, I think it makes more sense to keep the fullscreen button but remove the others.

**Comment by Gabriele-LS** [comment]
For sure it would be better to not have the buttons. To go full screen you can use the command in the menu or CMD + CTRL + F.

**Comment by JBraddockm** [comment]
You are right for the window capture. I was talking about Frameless mode, which I push to ATEM Mini Pro and use as an HDMI input.

**Comment by rse** [comment]
This cannot be introduced between 1.3.0 and 1.4.0, as no such styling was changed. Can this be a local problem? It looks like all texts are now zoomed for you because both the icons and the texts are larger now. Have you configured some sort of local display scaling or something like this? I've checked version 1.4.0 under macOS and for me it still looks just fine (see screenshot below). So, very strange...

<img width="839" alt="image" src="https://user-images.githubusercontent.com/221273/114175605-6a916b00-993a-11eb-9f3c-a134d75bfe2b.png">

**Comment by Gabriele-LS** [comment]
Hello @rse. Here you can see Vingester 1.3 and 1.4 side by side.

![Screenshot 2021-04-09 at 13 57 01](https://user-images.githubusercontent.com/67373152/114176509-85181400-993b-11eb-953b-c174e4b021d3.png)

**Comment by rse** [comment]
Very strange, very strange. I cannot repeat this myself under macOS... Hmmm...

**Comment by Gabriele-LS** [comment]
The issue is related to the font you used for the UI. Version 1.4 is using a different font compared to version 1.3.

**Comment by JBraddockm** [comment]
I have the same UI issue on my iMac that Gabriele has.

**Comment by rse** [comment]
Ok, under a different macOS system I was not able to repeat the problem. The difference between my primary macOS and your one seems to be that the fonts Vingester is using are for me also installed into the system. Perhaps this is the problem here. I'll roll a version 1.4.1 from scratch once I've verified the problem is now gone.

**Comment by rse** [comment]
Ok, it now is gone for me on the separate macOS system. I'll release 1.4.1 within a few minutes which will have this problem resolved. Thanks for reporting.

**Comment by Gabriele-LS** [comment]
Hello @rse, now the interface is back to normal. Regarding the three buttons in the top left corner of the window, now we have them appear and disappear automatically when you move the mouse pointer close to that corner (good!). But the fullscreen button is missing. I think, now that they disappear automatically, it would be good to have all the three buttons, as @JBraddockm requested.

**Comment by rse** [comment]
The appearing/disappearing I cannot get rid of as it looks. Making a browser fullscreen this way would not work as expected, as the underlying Chromium engine and Vingester really have to know that not just the window got larger but also that canvas of the Web Contents. Please resize browser windows only through the "Size" field of the control UI of Vingester.

**Comment by Gabriele-LS** [comment]
The appearing/disappearing behavior is perfect! But why there is not anymore the third button?

**Comment by rse** [comment]
Version 1.4.2 still has the bug that two "traffic light" buttons are still visible on hovering. In 1.4.3 I'm not trying to completely getting rid of those buttons as browser windows have to be controlled via the Vingester control UI only.
